steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute ssh dhruv_modi_opus@instance-20240905-064327 --zone asia-northeast1-b --command "~/deploy.sh"
