steps:
  Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Build the project
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']


  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    # entrypoint: 'bash'
    # args:
    #   - '-c'
    #   - |
    #     # SSH into the VM and deploy the app
    #     gcloud compute ssh dhruv_modi_opus@test-deploy --zone asia-northeast1-b --command "
    #       sudo apt update;
    #       curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -;
    #       sudo apt-get install -y nodejs;
    #       cd test-deploy;
    #       git pull origin master;
    #       npm install;
    #       npm run build;
    #       gcloud app deploy;
    #     "
